

package kotlinx.rpc.codegen.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link kotlinx.rpc.codegen.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("src/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("src/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("call.kt")
  public void testCall() {
    runTest("src/testData/box/call.kt");
  }

  @Test
  @TestMetadata("callStreaming.kt")
  public void testCallStreaming() {
    runTest("src/testData/box/callStreaming.kt");
  }

  @Test
  @TestMetadata("callStreamingSuspend.kt")
  public void testCallStreamingSuspend() {
    runTest("src/testData/box/callStreamingSuspend.kt");
  }

  @Test
  @TestMetadata("class.kt")
  public void testClass() {
    runTest("src/testData/box/class.kt");
  }

  @Test
  @TestMetadata("classWithChild.kt")
  public void testClassWithChild() {
    runTest("src/testData/box/classWithChild.kt");
  }

  @Test
  @TestMetadata("initCallableMap.kt")
  public void testInitCallableMap() {
    runTest("src/testData/box/initCallableMap.kt");
  }

  @Test
  @TestMetadata("localCall.kt")
  public void testLocalCall() {
    runTest("src/testData/box/localCall.kt");
  }
}
