

package kotlinx.rpc.codegen.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link kotlinx.rpc.codegen.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("customParameterTypes.kt")
  public void testCustomParameterTypes() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/box/customParameterTypes.kt");
  }

  @Test
  @TestMetadata("flowParameter.kt")
  public void testFlowParameter() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/box/flowParameter.kt");
  }

  @Test
  @TestMetadata("multiModule.kt")
  public void testMultiModule() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/box/multiModule.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/box/simple.kt");
  }
}
