

package kotlinx.rpc.codegen.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link kotlinx.rpc.codegen.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringDiagnostics")
@TestDataPath("$PROJECT_ROOT")
public class ColoringDiagnosticTestGenerated extends AbstractColoringDiagnosticTest {
  @Test
  public void testAllFilesPresentInColoringDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringDiagnostics"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("publicField.kt")
  public void testPublicField() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringDiagnostics/publicField.kt");
  }

  @Test
  @TestMetadata("simpleNoContext.kt")
  public void testSimpleNoContext() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringDiagnostics/simpleNoContext.kt");
  }
}
