

package kotlinx.rpc.codegen.test.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link kotlinx.rpc.codegen.test.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox")
@TestDataPath("$PROJECT_ROOT")
public class ColoringBoxTestGenerated extends AbstractColoringBoxTest {
  @Test
  public void testAllFilesPresentInColoringBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("classWithFields.kt")
  public void testClassWithFields() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/classWithFields.kt");
  }

  @Test
  @TestMetadata("closeLocalService.kt")
  public void testCloseLocalService() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/closeLocalService.kt");
  }

  @Test
  @TestMetadata("closeRemoteService.kt")
  public void testCloseRemoteService() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/closeRemoteService.kt");
  }

  @Test
  @TestMetadata("defaultValuesInConstructor.kt")
  public void testDefaultValuesInConstructor() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/defaultValuesInConstructor.kt");
  }

  @Test
  @TestMetadata("finalClass.kt")
  public void testFinalClass() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/finalClass.kt");
  }

  @Test
  @TestMetadata("functionWithContext.kt")
  public void testFunctionWithContext() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/functionWithContext.kt");
  }

  @Test
  @TestMetadata("noDefaultConstructor.kt")
  public void testNoDefaultConstructor() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/noDefaultConstructor.kt");
  }

  @Test
  @TestMetadata("returnFlow.kt")
  public void testReturnFlow() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/returnFlow.kt");
  }

  @Test
  @TestMetadata("serialize.kt")
  public void testSerialize() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/serialize.kt");
  }

  @Test
  @TestMetadata("severalConstructors.kt")
  public void testSeveralConstructors() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/severalConstructors.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/simple.kt");
  }

  @Test
  @TestMetadata("simpleImplicitSuspendAndOpen.kt")
  public void testSimpleImplicitSuspendAndOpen() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/simpleImplicitSuspendAndOpen.kt");
  }

  @Test
  @TestMetadata("simpleLocalContext.kt")
  public void testSimpleLocalContext() {
    runTest("/home/enotvtapke/work/kotlin-remote/compiler-plugin-tests/src/testData/coloringBox/simpleLocalContext.kt");
  }
}
