

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("anotherBoxTest.kt")
  public void testAnotherBoxTest() {
    runTest("compiler-plugin/testData/box/anotherBoxTest.kt");
  }

  @Test
  @TestMetadata("call.kt")
  public void testCall() {
    runTest("compiler-plugin/testData/box/call.kt");
  }

  @Test
  @TestMetadata("callStreaming.kt")
  public void testCallStreaming() {
    runTest("compiler-plugin/testData/box/callStreaming.kt");
  }

  @Test
  @TestMetadata("callStreamingSuspend.kt")
  public void testCallStreamingSuspend() {
    runTest("compiler-plugin/testData/box/callStreamingSuspend.kt");
  }

  @Test
  @TestMetadata("class.kt")
  public void testClass() {
    runTest("compiler-plugin/testData/box/class.kt");
  }

  @Test
  @TestMetadata("classWithChild.kt")
  public void testClassWithChild() {
    runTest("compiler-plugin/testData/box/classWithChild.kt");
  }

  @Test
  @TestMetadata("contextParameters.kt")
  public void testContextParameters() {
    runTest("compiler-plugin/testData/box/contextParameters.kt");
  }

  @Test
  @TestMetadata("extensionFunction.kt")
  public void testExtensionFunction() {
    runTest("compiler-plugin/testData/box/extensionFunction.kt");
  }

  @Test
  @TestMetadata("genericRemoteFunction.kt")
  public void testGenericRemoteFunction() {
    runTest("compiler-plugin/testData/box/genericRemoteFunction.kt");
  }

  @Test
  @TestMetadata("initCallableMap.kt")
  public void testInitCallableMap() {
    runTest("compiler-plugin/testData/box/initCallableMap.kt");
  }

  @Test
  @TestMetadata("localCall.kt")
  public void testLocalCall() {
    runTest("compiler-plugin/testData/box/localCall.kt");
  }

  @Test
  @TestMetadata("serializers.kt")
  public void testSerializers() {
    runTest("compiler-plugin/testData/box/serializers.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("compiler-plugin/testData/box/simple.kt");
  }
}
